Date valid
lugia-ysstech/lugia-web pull request #451
Opened 2020-04-06 12:39 UTC by cuicuiwang

2020-04-06 13:00 UTC, zenjava requested changes

2020-04-06 13:00 UTC, zenjava commented on src/widgets/date-picker/lugia.date-picker.zh-CN.json
> +    "ValidateType": ["top", "bottom"],
还有一种inner的方式

2020-04-06 13:00 UTC, zenjava commented on src/widgets/date-picker/lugia.date-picker.zh-CN.json
> +    "ValidateStatus": ["default", "error"],
默认验证状态参考下input组件

2020-04-06 13:00 UTC, zenjava commented on src/widgets/date-picker/lugia.date-picker.zh-CN.json
> +      "propsDefaultValue": "default"
与Input组件保持一致

2020-04-06 13:00 UTC, zenjava commented on src/widgets/date-picker/lugia.date-picker.zh-CN.json
> +      "propsDefaultValue": "default"
与Input组件保持一致。

2020-04-06 13:00 UTC, zenjava commented on src/widgets/date-picker/panel/RangeInput.js
> +            {validateStatus === 'error' && validateType === 'bottom' ? (
少实现了一种inner的校验方式。

2020-04-06 13:00 UTC, zenjava commented on src/widgets/date-picker/styled/styledRangeInput.js
> +export const ErrorTip = CSSComponent({
ErrorTip应该是复用Input里面的ErrorTip

2020-04-07 02:03 UTC, SleepyAries commented on src/widgets/date-picker/triggerPanel/rangePanelTrigger.js
> +      console.log('onChangeRange-blur', this.oldValue);
去除console

2020-04-07 02:03 UTC, SleepyAries commented on src/widgets/time-picker/lugia.time-picker.zh-CN.json
> +    "ValidateStatus": ["default", "error"],
参考Input组件状态

2020-04-10 09:05 UTC, SleepyAries commented on src/widgets/date-picker/lugia.date-picker.zh-CN.json
> +      "propsDefaultValue": "default"
propsDefaultValue 在Input组件中默认值是top

2020-04-10 09:05 UTC, SleepyAries commented on src/widgets/date-picker/lugia.month.zh-CN.json
> +      "propsDefaultValue": "default"
validateType 在Input组件中默认值是top

2020-04-23 04:38 UTC, closed without merging